### ISSUE TITLE
wich is next step - sorry im rookie in your application

### ISSUE THREAD

**Issue by johnfelipe** [reelyactive/barnowl-aruba#3]
This is all my steps

```
sudo apt install curl

curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -

echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

sudo apt update && sudo apt install yarn
```

yarn --version
1.22.19

# Using Ubuntu

```
curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash -

sudo apt-get install -y nodejs
```

node -v

v18.6.0

npm --version
8.13.2

```
apt -y install software-properties-common

git clone https://github.com/reelyactive/barnowl-aruba.git


npm install barnowl-aruba


cd barnowl-aruba

npm start
```

And nothing to see....
Pls share me a gist or readme.md for deploy an instance for show to my boss

Tnks

**Comment by jeffyactive** [comment]
Hi @johnfelipe, your next step is to [Configure an Aruba Instant AP](https://reelyactive.github.io/diy/aruba-instant-config/) to forward data to the computer on which you are running barnowl-aruba.  Then you will see Bluetooth Low Energy radio decodings printed to the console.

For a demo to your boss, you'll probably want to install [Pareto Anywhere](https://github.com/reelyactive/pareto-anywhere) which includes barnowl-aruba.  Then you can demo with the APIs and the [Pareto Anywhere Apps](https://reelyactive.github.io/pareto-anywhere-apps/).

Hope that helps!

**Comment by johnfelipe** [comment]
i need to show tomorrow 8 am COT, pls guide me for show something very good.
Pareto anywhere is possible install in docker for havent issues with services and ports and paths
can u guide me for install all enviroment with DEMO DATA?

**Comment by jeffyactive** [comment]
Yes, you can run Pareto Anywhere with Docker: https://github.com/reelyactive/pareto-anywhere#build-and-run-with-docker

Here are some demo dashboards:

- [CAPSpaces Demo](https://reelyactive.github.io/pareto-anywhere-apps/capspaces-demo/?demo=default)
- [Hyperlocal Context Explorer](https://reelyactive.github.io/pareto-anywhere-apps/hlc-explorer/?demo=default&updates=periodic)

**Comment by johnfelipe** [comment]
But how can put that demo dashboards in docker deployment?

**Comment by orlandingabriel** [comment]
Hello! I'm with the same problem. 
I've installed on a raspberry pi for debug with the barnowl-aruba. The console isn't printing anything.
Maybe because the documentation was created using ArubaOS 8, and now we are using the new AOS10, can you update please?
There's some information that is required right now and in AOS 8 was optional like authentication token or credentials (ws and wss). 
Thanks.

**Comment by jeffyactive** [comment]
Thanks @orlandingabriel, you're right that there are changes from AOS8 to AOS10 that we'll need to update for in barnowl-aruba.  We plan to work on this next week and will update this issue (and the identical Issue #4).

**Comment by jeffyactive** [comment]
The simple workaround for AOS 10 users is to load the AOS8 app from the IoT Connector App Store in order to continue using the AOS8 WebSocket interface. We've added a note in our [Configure an Aruba Instant AP](https://reelyactive.github.io/diy/aruba-instant-config/#prerequisites) tutorial.

If you have issues with this temporary workaround @orlandingabriel, kindly comment in #4.  Closing this issue.
