### ISSUE TITLE
Aruba AOS10

### ISSUE THREAD

**Issue by jonatangobbato** [reelyactive/barnowl-aruba#4]
Hello,

I have installed the application without problems but i use Aruba AOS10.
Can i have some help to make it works on Aruba AOS10?

**Comment by jeffyactive** [comment]
Thanks for flagging this @jonatangobbato, it's good to know that users like yourself are upgrading to AOS10.  There are a few changes from AOS8 that we'll need to accommodate for, which we plan to start working on next week.  I'll provide an update when there's a fix.

**Comment by jeffyactive** [comment]
The simple workaround for AOS 10 users is to load the AOS8 app from the IoT Connector App Store in order to continue using the AOS8 WebSocket interface.  We've added a note in our [Configure an Aruba Instant AP](https://reelyactive.github.io/diy/aruba-instant-config/#prerequisites) tutorial.

AOS 10 uses a new architecture which will allow us to complete novel integrations in the near future, which will be announced on the README.

Kindly close this issue @jonatangobbato if this temporary workaround works for you.

**Comment by jonatangobbato** [comment]
Hello @jeffyactive,

Thanks for the answer.

I tried to config using the AOS8 App from Aruba Central, but the Pareto does not seem to receive any information.
The config of the Aruba Central App seems a bit different of config in IAP.

No logs on Aruba Central side :(.

Do you have any experience using the AOS8 app in Aruba Central and Pareto?

**Comment by jeffyactive** [comment]
Thanks for giving this a try @jonatangobbato.  Can you provide a screenshot of the AOS8 App configuration (either here or via support@reelyactive.com)?  We currently don't have a setup to replicate this on our side.

If you see "Aruba WebSocket connection established" when running Pareto Anywhere from the command line, it means that Central (or an Instant AP) managed to connect with Pareto Anywhere.

**Comment by jonatangobbato** [comment]
Hello @jeffyactive, sorry for the delay to answer.

Follow de screenshots os AOS8 App configuration and  AOS10:

AOS 8 APP:

![image](https://user-images.githubusercontent.com/29125329/210791285-829a6fd1-03a9-4f3f-82d8-a4a7183e541c.png)

![image](https://user-images.githubusercontent.com/29125329/210791376-71b73478-f254-430a-92fb-b56469e5b734.png)

![image](https://user-images.githubusercontent.com/29125329/210791439-62e5e5a6-35a5-4e2d-8eac-c3342344a9bf.png)

![image](https://user-images.githubusercontent.com/29125329/210791554-de6cbce6-f12e-4794-8094-da95541fc16f.png)
Rules are Optional
![image](https://user-images.githubusercontent.com/29125329/210791661-6ebdfe5b-5539-4cb8-9488-8f54c0a04404.png)
External URLS are Optional
![image](https://user-images.githubusercontent.com/29125329/210791758-88ef5a57-5e03-44fd-809c-ccd9b9421f2b.png)
CA Certificate is optional
![image](https://user-images.githubusercontent.com/29125329/210792045-980ac5e3-4021-49cf-b554-2c145551d295.png)


AOS 10

![image](https://user-images.githubusercontent.com/29125329/210792259-68ac51d9-d1c6-4867-b653-11e2f44d1894.png)

On AOS10, only WSS service is allowed, when enter a URL on format "ws://someaddress" i get an error of invalid URL.

If you need more information, I'm happy to share.

**Comment by jeffyactive** [comment]
Thanks @jonatangobbato for the screenshots.  The AOS 8 App seems to provide all the required functionality, provided you can enable "BLE data forwarding" somewhere.  Can you use the AOS 8 App with "ws://someaddress"?  Or does the AOS 8 App require WSS too?  In other words, can you get it working with the AOS 8 App?

**Comment by jonatangobbato** [comment]
Hello @jeffyactive, sorry for the delay, i tested some options and no success on AOS8 App, since the problem with the AOS10 transport format is the TLS over Websocket, i created an TLS proxy in front of Pareto and connect the Aruba AOS10 with this proxy, i have success on the connection (lol).
![image](https://user-images.githubusercontent.com/29125329/214660109-0b583f06-cc03-4195-8559-b5f7c427fc9a.png)


Data are sent from Aruba to Pareto, but now i get an error on pareto when data is received:

![image](https://user-images.githubusercontent.com/29125329/214660365-f666a50e-94af-4619-936c-a524ef502c20.png)

**Comment by jeffyactive** [comment]
Hi @jonatangobbato, great that you are able to get the data through by adding TLS in front of Pareto Anywhere (we plan to document that soon, would be happy to know what procedure you followed to set that up).

The error message that you are seeing is almost certainly because your system (i.e. AOS version) is using a newer version of the protobuf specification than is included in barnowl-aruba.  In other words, we are not decoding the protobuf messages correctly.

We have the latest version of the protobuf from the Aruba Support Portal, and will incorporate this into the next version of barnowl-aruba.  Until then, I can't think of any workarounds for AOS10.  If this is a major blocker, feel free to [Contact Us](https://www.reelyactive.com/contact/#content) directly.  Thanks for your help and patience!

**Comment by jeffyactive** [comment]
Hi @jonatangobbato, after a year, we finally have good news: barnowl-aruba@1.4.0 supports the AOS10 protobuf specification.  And there's even a way to run secure WebSockets standalone, in a development environment (see the docs).  Thanks for your patience, marking as closed.
